### ISSUE TITLE
Improvements Requested

### ISSUE THREAD

**Issue by ALMaclaine** [ALMaclaine/tag-manager#3]
1. add align-items: flex-start to the tag-container
2. use font awesome for tag x https://www.npmjs.com/package/fa-svelte
3. add align-content: flex-start also so when tags wrap they don't flow to the center
4. Fix load more button focus/active state so that it matches button border radius
5. Allow multiple tags to be entered using commas
6. add input place holder text indicating commas possible
7. trim comma separated values to ensure trailing spaces aren't added to database
8. componentize elements for reuse

@lauras5

**Comment by lauras5** [comment]
1, 3 ,4. added tailwind classes to fix
2. updated x to font awesome 'times' symbol
5. added logic to add multiple classes with commas
6. updated placeholder text to 'separate tags with commas', lmk if you want to change it 
7. removed trailing spaces
8. moved the tag out into 'TagComponent' 

putting in new PR in for changes
